-- Add up migration script here
ALTER TABLE users_servers
ADD COLUMN owner BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN manage_channels BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN manage_users BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN manage_invites BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN banned BOOLEAN NOT NULL DEFAULT FALSE;
